version: '3.3'

services:
  icm:
    build:
      dockerfile: ./docker/production/Dockerfile
      context: .
    restart: unless-stopped
    tty: true
    environment:
      - DJANGO_ALLOWED_HOSTS=zabezpiecz.online
    volumes:
      - ./media:/app/media
      - ./db.sqlite3:/app/db.sqlite3

  nginx:
    image: nginx:alpine
    restart: unless-stopped
    environment:
      - NGINX_HOST=0.0.0.0
      - NGINX_PORT=80
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
      - ./media:/media
    ports:
      - 80:80