# Generated by Django 3.2.9 on 2021-11-23 20:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('service', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Entries',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('pass_model', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='service.pass')),
            ],
        ),
    ]
