# Generated by Django 3.2.9 on 2021-11-26 20:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('service', '0002_alter_client_card_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pass',
            name='pass_type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='service.passtype'),
        ),
        migrations.AlterField(
            model_name='pass',
            name='section',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='service.section'),
        ),
    ]
