# Generated by Django 3.2.9 on 2021-11-27 12:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('service', '0003_auto_20211126_2007'),
    ]

    operations = [
        migrations.AddField(
            model_name='instructor',
            name='last_login',
            field=models.DateTimeField(blank=True, null=True, verbose_name='last login'),
        ),
        migrations.AlterField(
            model_name='instructor',
            name='username',
            field=models.CharField(max_length=15, unique=True),
        ),
    ]
