# Generated by Django 3.2.9 on 2021-12-16 21:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('service', '0004_auto_20211127_1229'),
    ]

    operations = [
        migrations.AlterField(
            model_name='client',
            name='card_number',
            field=models.CharField(max_length=5, primary_key=True, serialize=False),
        ),
    ]
