# Generated by Django 3.2.9 on 2022-01-18 16:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('service', '0006_alter_client_card_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='instructor',
            name='username',
            field=models.EmailField(max_length=254, unique=True),
        ),
    ]
